In [3]:
# Array Definition
lst = [1,2,3,4]    # 1-dimensional array
lst1 = [[1,2,3]]    #2-dimensional array
lst2 = [[[1,2,3,4]]]      # 3-dimensional array

# Rasterization:
# Turning on the pixel at specific intensity is called Rasterization.
# Compueter only understand only 0 and 1 so they are justify true and false.so basically if we touch the screen then the pixel is on and if we don't touch it then the pixel is off and off is 0 and on is 1
#so computer will understand that the pixel is on or off. so this is called rasterization


# array stored the value of different data types
# any variable which is defined with the magntidue and direction is called vector.
# the numpy is vectorized form of array which consume less memory and less comuptational cost
# array preferred over array, n-dimensional and iterative process goes on looping so high consumption of computation and memory
################ Let's start with the numpy library
#Importing the numpy library
import numpy as np
#numpy --> Numerical Python
#np --> Alias lame of numpy
lst2 = [[[1,2,3,4]]]      # 3-dimensional array

# Rasterization:
# Turning on the pixel at specific intensity is called Rasterization.
# Compueter only understand only 0 and 1 so they are justify true and false.so basically if we touch the screen then the pixel is on and if we don't touch it then the pixel is off and off is 0 and on is 1
#so computer will understand that the pixel is on or off. so this is called rasterization


# array stored the value of different data types
# any variable which is defined with the magntidue and direction is called vector.
# the numpy is vectorized form of array which consume less memory and less comuptational cost
# array preferred over array, n-dimensional and iterative process goes on looping so high consumption of computation and memory
################ Let's start with the numpy library
#Importing the numpy library
import numpy as np
#numpy --> Numerical Python
#np --> Alias name of numpy


In [4]:
# Array defination

lst = [1,2,3,4]    # 1-dimensional array
print(type(lst))

<class 'list'>


In [5]:
# Numpy array defination

arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
# Array defination

lst1 = [[10,20,30,40]]

In [7]:
arry1 = np.array(lst1)

print(type(arry1))

<class 'numpy.ndarray'>


In [8]:
#Checking shape

print(arry1.shape)

(1, 4)


In [9]:
darray = [[[10,20,30],[40,50,60]]]

array =np.array(darray)

print(array.shape)

(1, 2, 3)


In [10]:
tarray = [[10,20,30],[40,50,60]]

array =np.array(tarray)

print(array.shape)

(2, 3)


In [11]:
# checking dimension of array

lst =  [10,20,30]

array =np.array(lst)

print(array.ndim)

1


In [12]:
lst =  [[10,20,30]]

array =np.array(lst)

print(array.ndim)

2


In [13]:
lst =  [[[10,20,30]]]

array =np.array(lst)

print(array.ndim)

3


In [14]:
lst =  [[[[10,20,30]]]]

array =np.array(lst)

print(array.ndim)

4


In [15]:
zeros = np.zeros((3,4))

print(zeros)
print(zeros.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
12


In [16]:
zeros.T      # T stands for Transpose

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
ones = np.ones((3,4))

print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
ones = np.array(ones)

'''
Whenever we use numpy array , by default the array contains float value
size =m*n where m : No. of rows and no. of columns
'''

print(ones.sum())
print(ones.sum(axis=0))   # This will perform operation column wise
print(ones.sum(axis=1))   # This will perform operation row wise

12.0
[3. 3. 3. 3.]
[4. 4. 4.]


In [19]:
array1 = np.array([[10,20],[30,40]])
array2 = np.array([[10,20],[30,40]])

array3 = array1 + array2
print(array3)

[[20 40]
 [60 80]]


In [20]:
a = array3.sum(axis = 0)
b = array3.sum(axis = 1)
print(a)
print(b)

[ 80 120]
[ 60 140]


In [21]:
eye = np.eye(4)

print(eye)   #kernel filter ---> 3*3 Matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
# Aggregrate Function

lst = [10,20,30,40]

a = np.array(lst)

print(a.sum())
print(a.max())
print(a.min())
print(a.var())
print(a.std())


100
40
10
125.0
11.180339887498949


In [23]:
a = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[100,200,300,400,500,600],
             [1000,2000,3000,4000,5000,6000]])

print(a)

[[   1    2    3    4    5    6]
 [  10   20   30   40   50   60]
 [ 100  200  300  400  500  600]
 [1000 2000 3000 4000 5000 6000]]


In [24]:
print(a[1:2,:2])

[[10 20]]


In [25]:
print(a[2:,3:5])

[[ 400  500]
 [4000 5000]]


In [26]:
print(a[2:,4:])

[[ 500  600]
 [5000 6000]]


In [27]:
print(a[:1,2:4])

[[3 4]]


In [28]:
# Question

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2,0,0],[0,2,0],[0,0,2]]).T
c = a*b

print(c.ndim)
print(c.size)
print(c.shape)
print(c)

2
9
(3, 3)
[[ 2  0  0]
 [ 0 10  0]
 [ 0  0 18]]


In [29]:
# Question

a = np.array([[1,2],[4,5],[7,8]])
b = np.array([[2,0],[0,2],[0,0]])
c = a*b

print(c.ndim)
print(c.size)
print(c.shape)
print(c)

2
6
(3, 2)
[[ 2  0]
 [ 0 10]
 [ 0  0]]


In [30]:
import pandas as pd
d = pd.DataFrame(c, columns=['a','b'])


In [31]:
d

a   b
0  2   0
1  0  10
2  0   0

In [32]:
num  = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(num)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [33]:
print(num.max(axis=1))
print(num.min(axis=0))
print(num.var())
print(num.std())

[ 3  6  9 12 15]
[1 2 3]
18.666666666666668
4.320493798938574


In [34]:
# Pandas library
import pandas as pd
#pandas : Library
# pd :Alias name
b = np.array([10,20,30,40])  # Numpy array

a= pd.Series(b) # 1Darray using Pandas Function
print(a)

a = pd.Series(b,index= ['IND','USA','UK','NZ'])
# 1D [One dimensional] array using Pandas Function
print(a)



0    10
1    20
2    30
3    40
dtype: int64
IND    10
USA    20
UK     30
NZ     40
dtype: int64


In [44]:
c = pd.Series([1,2,3,4,5])

c      # Series is an structured form of 1Dimensional array

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [35]:
print(a['UK'])

30


In [48]:
# 2D : Dimensional

c = pd.DataFrame({'IND': [10,20,30],'PAK': [100,200,300]})

print(c)



   IND  PAK
0   10  100
1   20  200
2   30  300


In [50]:
print(c['PAK'][2])

300


In [46]:
print(c.sum(axis=0))

IND     60
PAK    600
dtype: int64


In [47]:
print(c.sum(axis=1))

0    110
1    220
2    330
dtype: int64
